name: WolfOfWallStreet
main: TestPlugin.Wolf
version: 1.0
commands:
    PjSucks:
        description: What do you think?
    Balance:
        description: Your current balance.
    Give:
        description: Give player money.
    SetBalance:
        description: Set player balance.
    sell:
        description: Sell an item to the server.
        usage: /sell item amount price
    Buy:
<<<<<<< HEAD
        description: Buy an item from
=======
        descripton: Buy an item from the server.
        usage: /buy item amount
>>>>>>> f1c5bd05aa378e9edd0d0686dcebfa38913c836a
