name: WolfOfWallStreet
main: TestPlugin.Wolf
version: 1.0
commands:
    PjSucks:
        description: What do you think?
    Balance:
        description: Your current balance.
    Give:
        description: Give player money.
    SetBalance:
        description: Set player balance.
    sell:
        description: Sell an item to the server.
        usage: /sell item amount price
    Buy:
<<<<<<< HEAD
        description: Buy an item from the server.
=======
        description: Buy an item from
        descripton: Buy an item from the server.
>>>>>>> ac37102ee083f02d4e8f4d12af00581cfa9f2710
        usage: /buy item amount
