name: WolfOfWallStreet
main: TestPlugin.Wolf
version: 1.0
commands:
    PjSucks:
        description: What do you think?
    Balance:
        description: Your current balance.
    sell:
        description: Sell an item to the server.
        usage: /sell item amount price
    Buy:
        descripton: Buy an item from the server.
        usage: /buy item amount